### ISSUE TITLE
Unable to compile in Arduino 2.3.2

### ISSUE THREAD

**Issue by nextgenoperations** [gromeck/BLE-Scanner#25]
Would love to play with this but I am unable to use in 2.3.2.

I installed the board fine (got some other examples for BLE scanning and all works)...

I installed the libraries :

NimBLE 1.4.2
PubSubClient 2.8
via Library Manager 
and

Time 1.6.1 direct from GitHub...

When I compile i get a load of errors which I could start to try and work through, but I wondered if you had plans to update this at all ?

or perhaps at least mention the versions of the libraries that you used...

/Users/adam/Documents/Arduino/BLE-Scanner/watchdog.cpp: In function 'void WatchdogSetup(int)':
/Users/adam/Documents/Arduino/BLE-Scanner/watchdog.cpp:40:21: error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]
   40 |   esp_task_wdt_init(timeout, true);
      |                     ^~~~~~~
      |                     |
      |                     int
/Users/adam/Documents/Arduino/BLE-Scanner/watchdog.cpp:40:20: error: too many arguments to function 'esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t*)'
   40 |   esp_task_wdt_init(timeout, true);
      |   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from /Users/adam/Documents/Arduino/BLE-Scanner/watchdog.cpp:29:
/Users/adam/Library/Arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-442a798083/esp32/include/esp_system/include/esp_task_wdt.h:47:11: note: declared here
   47 | esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t *config);
      |           ^~~~~~~~~~~~~~~~~
/Users/adam/Documents/Arduino/BLE-Scanner/ntp.cpp: In function 'void NtpSetup()':
/Users/adam/Documents/Arduino/BLE-Scanner/ntp.cpp:178:7: error: 'WiFi' was not declared in this scope
  178 |   if (WiFi.hostByName(_config_ntp.server, _ntp_ip)) {
      |       ^~~~
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp: In function 'void EepromInit(int)':
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp:36:3: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   36 |   EEPROM.begin(_eeprom_size);
      |   ^~~~~~
      |   EPERM
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp: In function 'void EepromClear()':
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp:65:5: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   65 |     EEPROM.write(n, 0xff);
      |     ^~~~~~
      |     EPERM
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp:66:3: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   66 |   EEPROM.commit();
      |   ^~~~~~
      |   EPERM
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp: In function 'int EepromRead(int, int, void*)':
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp:80:9: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   80 |     if (EEPROM.read(addr + n) != 0xff)
      |         ^~~~~~
      |         EPERM
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp:87:28: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   87 |     ((byte *) buffer)[n] = EEPROM.read(addr + n);
      |                            ^~~~~~
      |                            EPERM
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp: In function 'void EepromWrite(int, int, const void*)':
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp:102:5: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
  102 |     EEPROM.write(addr + n, ((byte *) buffer)[n]);
      |     ^~~~~~
      |     EPERM
/Users/adam/Documents/Arduino/BLE-Scanner/eeprom.cpp:107:3: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
  107 |   EEPROM.commit();
      |   ^~~~~~
      |   EPERM
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp: In function 'bool WifiSetup()':
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:47:85: error: 'WiFi' was not declared in this scope
   47 |     strcpy(_AP_SSID, (String(WIFI_AP_SSID_PREFIX) + String(AddressToString((byte *) WiFi.macAddress(mac) + sizeof(mac) - WIFI_AP_SSID_USE_LAST_MAC_DIGITS, WIFI_AP_SSID_USE_LAST_MAC_DIGITS, false, ':'))).c_str());
      |                                                                                     ^~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:50:15: error: 'WIFI_AP' was not declared in this scope
   50 |     WiFi.mode(WIFI_AP);
      |               ^~~~~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:75:5: error: 'WiFi' was not declared in this scope
   75 |     WiFi.mode(WIFI_STA);
      |     ^~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:75:15: error: 'WIFI_STA' was not declared in this scope
   75 |     WiFi.mode(WIFI_STA);
      |               ^~~~~~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp: In function 'bool WifiUpdate()':
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:103:9: error: 'WiFi' was not declared in this scope
  103 |     if (WiFi.status() != WL_CONNECTED) {
      |         ^~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:103:26: error: 'WL_CONNECTED' was not declared in this scope
  103 |     if (WiFi.status() != WL_CONNECTED) {
      |                          ^~~~~~~~~~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp: In function 'String WifiGetSSID()':
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:137:53: error: 'WiFi' was not declared in this scope
  137 |   return StateCheck(STATE_CONFIGURING) ? _AP_SSID : WiFi.SSID();
      |                                                     ^~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp: In function 'int WifiGetChannel()':
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:145:10: error: 'WiFi' was not declared in this scope
  145 |   return WiFi.channel();
      |          ^~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp: In function 'int WifiGetRSSI()':
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:153:10: error: 'WiFi' was not declared in this scope
  153 |   return WiFi.RSSI();
      |          ^~~~
In file included from /Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:29:
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp: In function 'String WifiGetIpAddr()':
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:162:60: error: 'WiFi' was not declared in this scope
  162 |   return IPAddressToString(StateCheck(STATE_CONFIGURING) ? WiFi.softAPIP() : WiFi.localIP());
      |                                                            ^~~~
/Users/adam/Documents/Arduino/BLE-Scanner/util.h:63:37: note: in definition of macro 'IPAddressToString'
   63 | #define IPAddressToString(addr)   ((addr).toString())
      |                                     ^~~~
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp: In function 'String WifiGetMacAddr()':
/Users/adam/Documents/Arduino/BLE-Scanner/wifi.cpp:172:42: error: 'WiFi' was not declared in this scope
  172 |   return String(AddressToString((byte *) WiFi.macAddress(mac), sizeof(mac), false, ':'));
      |                                          ^~~~

exit status 1

Compilation error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]

**Comment by cybernetikaIO** [comment]
I'm also able to replicate the issue. This looks like an absolutely fantastic project and I'd love to look at extending it to a LilyGo TTGO with an external Bluetooth antenna port that would expand the range the device would be able to scan. 

My initial error that stops the compile is identical. Buy you a couple beers gromeck if we can figure this out? Cheers:

/home/opsadmin/Projects/BLE-Scanner/BLE-Scanner/watchdog.cpp: In function 'void WatchdogSetup(int)':
/home/opsadmin/Projects/BLE-Scanner/BLE-Scanner/watchdog.cpp:40:21: error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]
   40 |   esp_task_wdt_init(timeout, true);
      |                     ^~~~~~~
      |                     |
      |                     int
/home/opsadmin/Projects/BLE-Scanner/BLE-Scanner/watchdog.cpp:40:20: error: too many arguments to function 'esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t*)'
   40 |   esp_task_wdt_init(timeout, true);
      |   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from /home/opsadmin/Projects/BLE-Scanner/BLE-Scanner/watchdog.cpp:29:
/home/opsadmin/.arduino15/packages/esp32/tools/esp32-arduino-libs/idf-release_v5.1-bd2b9390ef/esp32/include/esp_system/include/esp_task_wdt.h:47:11: note: declared here
   47 | esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t *config);
      |           ^~~~~~~~~~~~~~~~~

exit status 1

Compilation error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]

**Comment by zurekx** [comment]
I have the same problem 
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\ntp.cpp: In function 'void NtpSetup()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\ntp.cpp:178:7: error: 'WiFi' was not declared in this scope
  178 |   if (WiFi.hostByName(_config_ntp.server, _ntp_ip)) {
      |       ^~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp: In function 'void EepromInit(int)':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp:36:3: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   36 |   EEPROM.begin(_eeprom_size);
      |   ^~~~~~
      |   EPERM
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp: In function 'void EepromClear()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp:65:5: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   65 |     EEPROM.write(n, 0xff);
      |     ^~~~~~
      |     EPERM
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp:66:3: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   66 |   EEPROM.commit();
      |   ^~~~~~
      |   EPERM
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp: In function 'int EepromRead(int, int, void*)':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp:80:9: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   80 |     if (EEPROM.read(addr + n) != 0xff)
      |         ^~~~~~
      |         EPERM
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp:87:28: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
   87 |     ((byte *) buffer)[n] = EEPROM.read(addr + n);
      |                            ^~~~~~
      |                            EPERM
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp: In function 'void EepromWrite(int, int, const void*)':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp:102:5: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
  102 |     EEPROM.write(addr + n, ((byte *) buffer)[n]);
      |     ^~~~~~
      |     EPERM
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\eeprom.cpp:107:3: error: 'EEPROM' was not declared in this scope; did you mean 'EPERM'?
  107 |   EEPROM.commit();
      |   ^~~~~~
      |   EPERM
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\watchdog.cpp: In function 'void WatchdogSetup(int)':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\watchdog.cpp:40:21: error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]
   40 |   esp_task_wdt_init(timeout, true);
      |                     ^~~~~~~
      |                     |
      |                     int
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\watchdog.cpp:40:20: error: too many arguments to function 'esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t*)'
   40 |   esp_task_wdt_init(timeout, true);
      |   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
In file included from D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\watchdog.cpp:29:
C:\Users\user\AppData\Local\Arduino15\packages\esp32\tools\esp32-arduino-libs\idf-release_v5.1-bd2b9390ef\esp32/include/esp_system/include/esp_task_wdt.h:47:11: note: declared here
   47 | esp_err_t esp_task_wdt_init(const esp_task_wdt_config_t *config);
      |           ^~~~~~~~~~~~~~~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp: In function 'bool WifiSetup()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:47:85: error: 'WiFi' was not declared in this scope
   47 |     strcpy(_AP_SSID, (String(WIFI_AP_SSID_PREFIX) + String(AddressToString((byte *) WiFi.macAddress(mac) + sizeof(mac) - WIFI_AP_SSID_USE_LAST_MAC_DIGITS, WIFI_AP_SSID_USE_LAST_MAC_DIGITS, false, ':'))).c_str());
      |                                                                                     ^~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:50:15: error: 'WIFI_AP' was not declared in this scope
   50 |     WiFi.mode(WIFI_AP);
      |               ^~~~~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:75:5: error: 'WiFi' was not declared in this scope
   75 |     WiFi.mode(WIFI_STA);
      |     ^~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:75:15: error: 'WIFI_STA' was not declared in this scope
   75 |     WiFi.mode(WIFI_STA);
      |               ^~~~~~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp: In function 'bool WifiUpdate()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:103:9: error: 'WiFi' was not declared in this scope
  103 |     if (WiFi.status() != WL_CONNECTED) {
      |         ^~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:103:26: error: 'WL_CONNECTED' was not declared in this scope
  103 |     if (WiFi.status() != WL_CONNECTED) {
      |                          ^~~~~~~~~~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp: In function 'String WifiGetSSID()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:137:53: error: 'WiFi' was not declared in this scope
  137 |   return StateCheck(STATE_CONFIGURING) ? _AP_SSID : WiFi.SSID();
      |                                                     ^~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp: In function 'int WifiGetChannel()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:145:10: error: 'WiFi' was not declared in this scope
  145 |   return WiFi.channel();
      |          ^~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp: In function 'int WifiGetRSSI()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:153:10: error: 'WiFi' was not declared in this scope
  153 |   return WiFi.RSSI();
      |          ^~~~
In file included from D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:29:
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp: In function 'String WifiGetIpAddr()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:162:60: error: 'WiFi' was not declared in this scope
  162 |   return IPAddressToString(StateCheck(STATE_CONFIGURING) ? WiFi.softAPIP() : WiFi.localIP());
      |                                                            ^~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\util.h:63:37: note: in definition of macro 'IPAddressToString'
   63 | #define IPAddressToString(addr)   ((addr).toString())
      |                                     ^~~~
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp: In function 'String WifiGetMacAddr()':
D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\wifi.cpp:172:42: error: 'WiFi' was not declared in this scope
  172 |   return String(AddressToString((byte *) WiFi.macAddress(mac), sizeof(mac), false, ':'));
      |                                          ^~~~

exit status 1

Compilation error: 'WiFi' was not declared in this scope

**Comment by gromeck** [comment]
Sorry for not responding earlier.


> Would love to play with this but I am unable to use in 2.3.2.
> 
> I installed the board fine (got some other examples for BLE scanning and all works)...

Which board did you install resp. trying to compile for?

**Comment by gromeck** [comment]
> I'm also able to replicate the issue. This looks like an absolutely fantastic project and I'd love to look at extending it to a LilyGo TTGO with an external Bluetooth antenna port that would expand the range the device would be able to scan. I am currently using the WEMOS D1 MINI ESP32 to minimize board-difference issues and work to a functional baseline.

Hmm, so it works with WEMOS D1 MINI ESP32 and the errors happen during the compilation for LilyGo?

**Comment by gromeck** [comment]
> I have the same problem

no, you don't ...

> D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\ntp.cpp: In function 'void NtpSetup()': D:\ESP32\BLE-Scanner-main\BLE-Scanner-main\BLE-Scanner\ntp.cpp:178:7: error: 'WiFi' was not declared in this scope 178

The WiFi library is missing ... it should be part of the esp32 package.
Same is true for the EEPROM lib.

**Comment by cybernetikaIO** [comment]
> > I'm also able to replicate the issue. This looks like an absolutely fantastic project and I'd love to look at extending it to a LilyGo TTGO with an external Bluetooth antenna port that would expand the range the device would be able to scan. I am currently using the WEMOS D1 MINI ESP32 to minimize board-difference issues and work to a functional baseline.
> 
> Hmm, so it works with WEMOS D1 MINI ESP32 and the errors happen during the compilation for LilyGo?

Indeed you're right! I added those libraries in and made it far further but hit the invalid conversion from int to const error in watchdog.cpp:

/home/opsadmin/Projects/BLE-Scanner/BLE-Scanner/watchdog.cpp:53:21: error: invalid conversion from 'int' to 'const esp_task_wdt_config_t*' [-fpermissive]
   53 |   esp_task_wdt_init(timeout, true);

I am compiling to the WEMOS D1 MINI ESP32. Thoughts? Thank you again.

**Comment by gromeck** [comment]
I'm still using Arduino IDE 1.x.
Did you try to define `timeout` as `const int` (instead of currently `int`) in `watchdog.cpp`?

**Comment by gromeck** [comment]
sorry, no, that will not work ... it looks like the interface has changed.

**Comment by gromeck** [comment]
Ok, I verified that the ESP API  V4.x to V5.x changed the interface of the watchdog ... I will come back soon with a patch.

**Comment by gromeck** [comment]
Commit a7549bd1585405b026f78bb047ef88eaaf769630 fixes the problem with this changed API

Verified also under Arduino IDE 2.3.2

**Comment by RCCRAFT1** [comment]
Hi, I'm having the same problem when compiling. Has anyone else found a fix for this yet? I'm on IDE 2.3.10

**Comment by gromeck** [comment]
Would you like to provide some more details?

**Comment by RCCRAFT1** [comment]
I mean, I'm getting the same errors as the person who first opened the issue... I'm running IDE 2.3.10 on an ARM MacBook Pro. I made sure to install all the dependencies before running the sketch
